global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'hobbit_qa'
    static_configs:
      - targets: ['hobbit_qa:8000']  # Assuming the app exposes metrics on port 8000

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
